### ISSUE TITLE
Max 2022 support

### ISSUE THREAD

**Issue by smabukhari** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMaxPlugin#8]
Please add Max 2022 Support to RPR

**Comment by bsavery** [comment]
Have you tried the latest build installer?  (In releases).  I have not myself but some users reported it worked on 2022

**Comment by smabukhari** [comment]
Hi Yes I tried it but it doesn't work - it gives loading error

**Comment by smabukhari** [comment]
After extensive research I found out that 3ds max 2022 SDK is a break. Therefore plugins need to be updated for 3ds max 2022. Please provide 2022 support for RPR

**Comment by bsavery** [comment]
We are not planning to update the plugin ourselves until support for USD / Hydra is added to 3DSMax which they have announced but not given a version for yet.  However we are open source.  It's possible the build here could be modified to work with 3dsmax 2022 and we would certainly accept code contributions...

**Comment by uro666** [comment]
Apologies for adding to a closed issue thread, but it seemed the most correct course of action since it is the same topic rather than starting a new issue.

Autodesk released **USD for Max v0.1** in an open beta as a standalone installer for the 3ds Max 2022.1 update last week.

Release Notes - https://help.autodesk.com/view/3DSMAX/2022/ENU/?guid=GUID-F53F713B-6A6F-49A2-A371-7C1CCEC87199

Autodesk are already implementing USD with their own Arnold renderer - https://github.com/Autodesk/arnold-usd

**Comment by bsavery** [comment]
Hello @Uro1 .  That is just import / export.  They should have USD hydra support coming soon (which is what we need).  USD Hydra allows using USD based renderers, the beta plugin just allows importing and exporting files from 3dsmax.

That said, if you want to export a USD from max with that and use with our USD Hydra delegate to render you can!
